### ISSUE TITLE
AccessDeniedException keeps getting thrown inside SpringBoot request

### ISSUE THREAD

**Issue by Demoniaque** [atomashpolskiy/bt#107] opened 2019-01-19 19:26 UTC
I'm sending torrent links from an external third party into my server. Springboot takes the request and downloads the torrent. However, BT keeps crashing with an AccessDeniedException without any further context. It says that Files.delete is throwing the exception which makes sense as it's the only method that can crash with such an error.

Here's my code:
https://hasteb.in/aradumew.java

The error thrown is:
https://hasteb.in/tameyiqu.sql

Am I doing something wrong?

The other issue on this repo says that the error has been made more verbose but that release hasn't appeared on maven in a very long time and it's not even a solution to the issue.

This stackoverflow thread mentions File.delete can cause this crash if something tries to reopen the file after it's marked to be deleted. https://stackoverflow.com/a/31608180/4327834

**Comment by atomashpolskiy** [comment] 2019-01-21 12:41
I guess the underlying issue does not need a solution, because it's just a log message and does not really affect anything.

**Comment by Demoniaque** [comment] 2019-01-21 12:43
the app crashes, it's not a harmless log message

**Comment by atomashpolskiy** [comment] 2019-01-21 13:03
If you're referencing [this issue](https://github.com/atomashpolskiy/bt/issues/90), the message is logged [here](https://github.com/atomashpolskiy/bt/blob/81e878d1ae908416d8c38d48c99e34d4b425926b/bt-dht/the8472/mldht/src/the8472/utils/AnonAllocator.java#L39) in current master and [here](https://github.com/atomashpolskiy/bt/blob/a7aa17e863c15ddb42417dc33403278586e4cbac/bt-dht/the8472/mldht/src/the8472/utils/AnonAllocator.java#L40) in 1.7 release. Obviously, it's quite harmless. What makes you think that your app crashes?

**Comment by Demoniaque** [comment] 2019-01-26 19:01
Perhaps the app doesn't crash, but the torrent downloading certainly ceases to function. No console logs beyond that error message and I've waited on it for a really long time. The torrent I'm testing with is like 2MB and I was able to successfully download it using Deluge.

**Comment by atomashpolskiy** [comment] 2019-01-26 19:40
It's the other way around: Bt does not terminate because of the error, but rather the error happens (and the log message is printed) when Bt terminates. There may be three reasons for Bt to terminate: either the JVM process has received a termination signal from the operating system, or it was explicitly asked to shutdown/stop by the application code, or the runtime has been configured to stop when the download has completed (I think this should be your case, so check if the files have been downloaded). If you have any doubts, don't wait, check what your application is doing with `jstack`. Also, you don't need to stop the client explicitly, if `stopWhenDownloaded()` is set (there should not be any harm in doing this though, it's just not necessary).

**Comment by atomashpolskiy** [comment] 2019-01-26 20:18
Great to hear that the issue is resolved, closing now

**Closed by atomashpolskiy** 2019-01-26 20:18 UTC

**Comment by Demoniaque** [comment] 2019-01-26 20:50
Actually, is it possible to suppress the error messages? I rely on my console for debug purposes and the errors keep spamming it.

**Comment by Demoniaque** [comment] 2019-01-26 20:51
also I found another unusual bug where my download gets stuck at 98.9%. I kept the same torrent going for an hour and it never stopped

**Comment by atomashpolskiy** [comment] 2019-01-26 21:47
> Actually, is it possible to suppress the error messages? I rely on my console for debug purposes and the errors keep spamming it.

Bt uses slf4j, so you need to setup your logger.

> also I found another unusual bug where my download gets stuck at 98.9%

Yeah, I'm aware of this. Unfortunately, I'm not sure what's causing it.

**Comment by Demoniaque** [comment] 2019-02-03 20:13
Although that is unfortunate, is there a way to circumvent the issue? If there's a way to detect when it happens maybe? Temporary solutions?
